"""create car_info additional_info

Revision ID: bffd18a2d10f
Revises: 822a816ef189
Create Date: 2026-01-16 16:14:31.844133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffd18a2d10f'
down_revision: Union[str, Sequence[str], None] = '822a816ef189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('car_info', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('additional_info', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'additional_info')
    op.drop_column('users', 'car_info')
    # ### end Alembic commands ###
